### ISSUE TITLE
[Issue] Error

### ISSUE THREAD

**Issue by Hyronymos1337** [GC-spigot/AdvancedSpawners#134]
Error: https://privatebin.net/?8f6f1652153caff7#CH24XEqXJn9D6xyMHyoBXtMTtzox7Zi9RtGuXjNA6RJV

 - Minecraft Version: 1.16.1
- Plugin Version: latest

**Comment by GC-spigot** [comment]
Fixed

**Comment by Hyronymos1337** [comment]
not fixed, using latest version

error: https://privatebin.net/?771ab9ef570d9a5b#BJSPdZ5u9xqCAus8qK64ny8CBsDCE3QeX8CxnMUVqQ4k
